"""add_subscription_fields

Revision ID: 903a4798368d
Revises: 10ee75c6f7fa
Create Date: 2026-06-15 22:25:30.641000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903a4798368d'
down_revision: Union[str, Sequence[str], None] = '10ee75c6f7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_valid_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_valid_until')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'subscription_plan')
    # ### end Alembic commands ###
